name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g @cloudflare/wrangler
      - name: Set Compatibility Date
        run: echo "COMPATIBILITY_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Publish to Cloudflare Workers
        env:
          COMPATIBILITY_DATE: ${{ env.COMPATIBILITY_DATE }}
        run: npx wrangler publish
